"""
Generates a labeled training session for scripts/train_*.py.

CLAUDE.md Section 8 / synopsis Section 5.3: no external labelled attack
dataset -- every model trains on data generated by this project's own
testbed. This script reuses the SAME reading-generation logic as
`device_simulator.py` (imports it directly, does not reimplement it) so
the offline-trained models see exactly the same kind of telemetry the
live simulated devices produce, just captured to a file instead of
streamed over MQTT. Once you have a real physical adversarial-testing
session (synopsis Section 4.2 Stage 6 -- tap/shock the rig, loosen a
mount, disconnect a sensor, capture what the real ESP32 reports), replace
or augment this synthetic session with `data/collected/adversarial_*.json`
recorded from data/collected -- every train_*.py script here reads the
same JSON shape, so swapping in real data doesn't require touching them.

Output: data/collected/training_session.json -- a list of records:
{tick, device_id, reading (float or feature dict), auth_ok, ts, label,
event_type}. `label` (1=legitimate, 0=suspicious) is the ground truth
this synthetic session KNOWS because it generated the anomalies itself --
this is qualitatively different from (and more defensible than) the live
gateway's pseudo-label heuristic, which only ever gets to *guess* at
ground truth from auth+range checks. See CLAUDE.md Section 8's "no
external labelled datasets" constraint -- this is the labelled set that
satisfies it.
"""

import json
import os
import random
import sys
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from config import DEVICE_REGISTRY, DATA_COLLECTED_DIR
import device_simulator as ds

TICKS = 400            # 400 ticks * 3 devices ~= enough history for every scorer's min-training-size
OUTPUT_PATH = os.path.join(DATA_COLLECTED_DIR, "training_session.json")


def generate(ticks: int = TICKS, seed: int = 42) -> list[dict]:
    random.seed(seed)
    records = []
    base_ts = 60_000  # start at 60s of simulated uptime, matches the "past the reboot grace window" realistic case
    for tick in range(ticks):
        coordinated_tick = tick % 25 == 3  # mirrors device_simulator.py's live cadence exactly
        for device_id, info in DEVICE_REGISTRY.items():
            anomalous = device_id == "esp32-vib-001" and tick % 12 == 7
            coordinated = coordinated_tick and not anomalous
            auth_ok = not (device_id == "actuator-001" and tick % 15 == 9)
            reading = ds.make_reading(device_id, anomalous=anomalous, coordinated=coordinated)
            ts = base_ts + tick * 2000 + (0 if device_id != "esp32-vib-001" else 5)

            label = 1
            event_type = "normal"
            if not auth_ok:
                label = 0
                event_type = "forged_signature"
            elif anomalous:
                label = 0
                event_type = "anomalous_shock"
            elif coordinated:
                # Individually in-range (no rule-based override), suspicious
                # only as a cross-device pattern -- see gnn_scorer.py /
                # module docstring. Ground truth is 0 for ALL THREE devices
                # in this tick, not just one -- that co-occurrence IS the
                # attack signature.
                label = 0
                event_type = "coordinated"
            elif device_id != "esp32-vib-001":
                lo, hi = info["expected_range"]
                if not (lo <= reading <= hi):
                    label = 0
                    event_type = "out_of_range"

            records.append({
                "tick": tick,
                "device_id": device_id,
                "reading": reading,
                "auth_ok": auth_ok,
                "ts": ts,
                "label": label,
                "event_type": event_type,
            })

        # occasional replay event, mirroring device_simulator.py's live replay injection
        if tick % 20 == 14 and tick > 0:
            prior = [r for r in records if r["device_id"] == "esp32-vib-001" and r["event_type"] == "normal"]
            if prior:
                replayed = dict(random.choice(prior))
                replayed["tick"] = tick
                replayed["label"] = 0
                replayed["event_type"] = "replay"
                records.append(replayed)

    return records


def main():
    os.makedirs(DATA_COLLECTED_DIR, exist_ok=True)
    records = generate()
    with open(OUTPUT_PATH, "w") as f:
        json.dump(records, f, indent=1)
    by_event = {}
    for r in records:
        by_event[r["event_type"]] = by_event.get(r["event_type"], 0) + 1
    print(f"wrote {len(records)} records to {OUTPUT_PATH}")
    print("event type breakdown:", by_event)


if __name__ == "__main__":
    main()
