"""
The figure set for the corrected-M6 paper evidence (2026-09-07, two passes).
Supersedes every figure previously under docs/figures/ (fig1-fig17,
figA-figD from generate_evaluation_graphs.py / generate_paper_figures.py) --
those were generated before the comparator repair and the corrected-M6
promotion and were deleted when this script first landed (see git history
to recover them).

Two tiers, both always regenerated by main():
  - PAPER_FIGURES: model_performance_comparison, policy_action_performance,
    hardware_validation, local_detector_attack_class_recall,
    m6_training_correction, pending_node_masking_correction -- a refined,
    priority-ranked set added in the second pass. These SUPERSEDED (replaced
    outright, not left redundant) the original R1/R3/R4/R5/R6/R14 with more
    precisely specified panels (e.g. model_performance_comparison combines
    what R1/R3/R8 showed separately; policy_action_performance switched from
    a two-arm GCN-vs-M6 comparison to a single-arm precision/recall/F1
    diagnostic of the actually-deployed policy).
  - The remaining R-numbered figures (R2, R7-R13, R15) from the first pass,
    unaffected by the refinement.

Every figure reads directly from a results/*.json or results/*.log artifact,
or recomputes with the exact same replay logic an evaluate_*.py script uses
(never a second implementation) -- no number here is invented. Where an
artifact is GCN-era/preserved (the local-detector attack-recall figure's
per-signal log predates the M6 switch), the figure says so in its
title/caption, matching docs/paper/13's own
[VERIFIED PRESERVED GCN-ERA REPLAY] labelling.

    python scripts/generate_corrected_m6_figures.py
"""
import csv
import json
import os
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
sys.path.insert(0, os.path.dirname(__file__))

import joblib

ROOT = os.path.join(os.path.dirname(__file__), "..")
FIGURES_DIR = os.path.join(ROOT, "docs", "figures")
os.makedirs(FIGURES_DIR, exist_ok=True)

# Same palette as generate_paper_figures.py, extended with one more slot for
# a third comparison arm (gcn / m6_deployed-flawed / m6_corrected).
CYAN, VIOLET, AMBER, RED, GREY = "#2aa9b5", "#7c5cd6", "#d8a33a", "#c8503f", "#8a8f98"
ARM_COLOR = {"gcn": GREY, "m6_deployed": RED, "m6_corrected": CYAN,
             "gcn_corrected": GREY, "flawed": RED, "corrected": CYAN}
ARM_LABEL = {"gcn": "GCN", "m6_deployed": "M6 (deployed, flawed)",
             "m6_corrected": "M6 (corrected)", "gcn_corrected": "GCN (fair baseline)"}


def savefig(fig, name):
    path = os.path.join(FIGURES_DIR, name)
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"wrote {path}")


def rj(relpath):
    with open(os.path.join(ROOT, relpath)) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# R2 -- M1-M9 relational benchmark (High)
# ---------------------------------------------------------------------------
def r2_m1_m9_benchmark():
    d = rj("results/crossdevice_benchmark/metrics.json")["results"]
    names = list(d.keys())
    macro_f1 = [d[n]["test_macro_f1"] for n in names]
    fpr = [d[n]["test"]["false_positive_rate"] for n in names]
    labels = [n.split("_", 1)[1].replace("_", " ") for n in names]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4.6), sharey=True)
    y = np.arange(len(names))
    colors = [CYAN if n == "M6_set_transformer" else (RED if n == "M4_gcn" else VIOLET) for n in names]
    ax1.barh(y, macro_f1, color=colors)
    ax1.set_yticks(y)
    ax1.set_yticklabels(labels, fontsize=8)
    ax1.invert_yaxis()
    ax1.set_xlabel("Test Macro-F1")
    ax1.set_xlim(0, 1.05)
    for yi, v in zip(y, macro_f1):
        ax1.text(v + 0.01, yi, f"{v:.4f}", va="center", fontsize=7)

    ax2.barh(y, fpr, color=colors)
    ax2.set_xlabel("Test FPR")
    for yi, v in zip(y, fpr):
        ax2.text(v + 0.002, yi, f"{v:.4f}", va="center", fontsize=7)

    fig.suptitle("R2: M1-M9 standalone relational benchmark (20-node constructed network, "
                  "seed 0, doc 13 B)", y=1.02)
    savefig(fig, "r2_m1_m9_benchmark.png")


# ---------------------------------------------------------------------------
# R7 -- GCN vs M6 latency (Medium)
# ---------------------------------------------------------------------------
def r7_latency():
    d = rj("results/gcn_m6_corrected_comparison/latency_comparison.json")["results"]
    arms = ["gcn", "m6_deployed", "m6_corrected"]

    fig, ax = plt.subplots(figsize=(6.5, 4.4))
    x = np.arange(len(arms))
    mean = [d[a]["mean_ms"] for a in arms]
    p95 = [d[a]["p95_ms"] for a in arms]
    width = 0.35
    ax.bar(x - width / 2, mean, width, label="mean", color=[ARM_COLOR[a] for a in arms])
    ax.bar(x + width / 2, p95, width, label="p95", color=[ARM_COLOR[a] for a in arms], alpha=0.5)
    for xi, v in zip(x - width / 2, mean):
        ax.text(xi, v + 0.05, f"{v:.2f}", ha="center", fontsize=8)
    for xi, v in zip(x + width / 2, p95):
        ax.text(xi, v + 0.05, f"{v:.2f}", ha="center", fontsize=8)
    ax.set_xticks(x)
    ax.set_xticklabels([ARM_LABEL[a] for a in arms], fontsize=8)
    ax.set_ylabel("Latency (ms)")
    ax.set_title("R7: Standalone relational-scorer inference latency\n"
                  "(post-warmup, n=200 calls, doc 13 O4)")
    ax.legend(fontsize=8)
    ax.grid(axis="y", alpha=0.25)
    savefig(fig, "r7_latency.png")


# ---------------------------------------------------------------------------
# R8 -- Fusion comparison (High)
# ---------------------------------------------------------------------------
def r8_fusion_comparison():
    d = rj("results/gcn_m6_corrected_comparison/fusion_comparison.json")["results"]
    arms = ["gcn", "m6_deployed", "m6_corrected"]
    metrics = ["macro_f1", "roc_auc", "recall_normal", "false_alarm_rate_fpr"]
    metric_labels = ["Macro-F1", "ROC-AUC", "Recall\n(normal)", "FPR"]

    fig, ax = plt.subplots(figsize=(8.5, 4.6))
    x = np.arange(len(metrics))
    width = 0.26
    for i, arm in enumerate(arms):
        vals = [d[arm][m] for m in metrics]
        ax.bar(x + (i - 1) * width, vals, width, label=ARM_LABEL[arm], color=ARM_COLOR[arm])
        for xi, v in zip(x + (i - 1) * width, vals):
            ax.text(xi, v + 0.015, f"{v:.3f}", ha="center", va="bottom", fontsize=7, rotation=90)
    ax.set_xticks(x)
    ax.set_xticklabels(metric_labels)
    ax.set_ylim(0, 1.05)
    ax.set_title("R8: Fusion comparison — rule+IF+LSTM+relational, matched fusion per arm\n"
                  "(held-out replay, doc 13 O4; both M6 variants beat GCN modestly)")
    ax.legend(fontsize=8)
    ax.grid(axis="y", alpha=0.25)
    savefig(fig, "r8_fusion_comparison.png")


# ---------------------------------------------------------------------------
# R9 -- Topology sensitivity (Medium)
# ---------------------------------------------------------------------------
def r9_topology_sensitivity():
    sp = rj("results/crossdevice_benchmark/metrics.json")["structural_probes"]["neighbour_degree_at_n10"]
    models = list(sp.keys())
    colors = {"M3_deep_sets": VIOLET, "M4_gcn": RED, "M5_gatv2": AMBER, "M6_set_transformer": CYAN,
              "M7_np_st": "#1f6f5c", "M8_set_transformer_mixed_n": "#5c4a1f"}

    fig, ax = plt.subplots(figsize=(7, 4.4))
    for m in models:
        degrees = sorted(int(k) for k in sp[m].keys())
        recall = [sp[m][str(k)]["recall_at_threshold"] for k in degrees]
        ax.plot(degrees, recall, marker="o", label=m.split("_", 1)[1].replace("_", " "),
                color=colors.get(m, GREY))
    ax.set_xlabel("Active neighbour degree (n=10)")
    ax.set_ylabel("Recall at frozen threshold")
    ax.set_ylim(0, 1.05)
    ax.set_title("R9: Target-degree topology-sensitivity probe\n"
                  "(400 synthetic draws/cell, fixed threshold, doc 13 D)")
    ax.legend(fontsize=8)
    ax.grid(alpha=0.25)
    savefig(fig, "r9_topology_sensitivity.png")


# ---------------------------------------------------------------------------
# R10 -- Generator validity / OOD behavior (Medium)
# ---------------------------------------------------------------------------
def r10_generator_validity():
    # source: results/final_verification/generator_validation.log, doc 13 I
    regimes = ["LOW", "MEDIUM", "HIGH"]
    spread = [0.00794, 0.01509, 0.03842]
    status = ["Pass all four\nmeasured coords", "RMS marginal\ndivergence", "RMS+peak marginal\ndivergence"]
    colors = [CYAN, AMBER, RED]

    fig, ax = plt.subplots(figsize=(6, 4.4))
    bars = ax.bar(regimes, spread, color=colors)
    for b, s in zip(bars, status):
        ax.text(b.get_x() + b.get_width() / 2, b.get_height() + 0.001, s,
                ha="center", va="bottom", fontsize=7.5)
    ax.set_ylabel("Cross-node RMS spread")
    ax.set_title("R10: Virtual-generator validity boundary\n"
                  "(TRAIN residual consistency, LOW/MEDIUM/HIGH presets, doc 13 I)")
    ax.grid(axis="y", alpha=0.25)
    savefig(fig, "r10_generator_validity.png")


# ---------------------------------------------------------------------------
# R11 -- Explainability contribution distribution (Optional)
# ---------------------------------------------------------------------------
def r11_explainability_contributions():
    gcn = joblib.load(os.path.join(ROOT, "models", "fusion_meta_learner_gcn_backup.joblib"))
    m6c = joblib.load(os.path.join(ROOT, "models", "fusion_meta_learner_m6_corrected_variant.joblib"))
    channels = ["rule", "IF", "LSTM-AE", "relational"]

    fig, ax = plt.subplots(figsize=(6.5, 4.4))
    x = np.arange(len(channels))
    width = 0.35
    ax.bar(x - width / 2, gcn.coef_[0], width, label="GCN fusion", color=GREY)
    ax.bar(x + width / 2, m6c.coef_[0], width, label="Corrected-M6 fusion", color=CYAN)
    ax.axhline(0, color="black", lw=0.8)
    ax.set_xticks(x)
    ax.set_xticklabels(channels)
    ax.set_ylabel("Logistic-regression coefficient (log-odds weight)")
    ax.set_title("R11: Fusion input-channel contribution — GCN vs. corrected-M6\n"
                  "(saved fusion_meta_learner coefficients, doc 13 O2)")
    ax.legend(fontsize=8)
    ax.grid(axis="y", alpha=0.25)
    savefig(fig, "r11_explainability_contributions.png")


# ---------------------------------------------------------------------------
# R12 -- Policy confusion matrix (Optional)
# ---------------------------------------------------------------------------
def r12_policy_confusion_matrix():
    def load_csv(name):
        path = os.path.join(ROOT, "results", "m6_corrected_policy", name)
        with open(path) as f:
            rows = list(csv.reader(f))
        header = rows[0][1:]
        matrix = np.array([[int(v) for v in r[1:]] for r in rows[1:]], dtype=float)
        return header, matrix

    fig, axes = plt.subplots(1, 2, figsize=(10, 4.6))
    for ax, (name, title) in zip(axes, [
        ("confusion_matrix_m6_corrected_policy_gcn_corrected.csv", "GCN (fair baseline)"),
        ("confusion_matrix_m6_corrected_policy_m6_corrected.csv", "Corrected M6"),
    ]):
        labels, m = load_csv(name)
        row_norm = m / m.sum(axis=1, keepdims=True)
        im = ax.imshow(row_norm, cmap="Blues", vmin=0, vmax=1)
        ax.set_xticks(range(len(labels)))
        ax.set_xticklabels(labels, fontsize=8)
        ax.set_yticks(range(len(labels)))
        ax.set_yticklabels(labels, fontsize=8)
        ax.set_xlabel("Predicted")
        ax.set_ylabel("Actual")
        ax.set_title(title, fontsize=9)
        for i in range(len(labels)):
            for j in range(len(labels)):
                ax.text(j, i, int(m[i, j]), ha="center", va="center",
                        fontsize=8, color="white" if row_norm[i, j] > 0.5 else "black")
    fig.suptitle("R12: Policy confusion matrix (rows: actual, columns: predicted; "
                 "test_session.json, deterministic clock)", y=1.03)
    savefig(fig, "r12_policy_confusion_matrix.png")


# ---------------------------------------------------------------------------
# R13 -- Hardware score distributions (Very useful if artifacts support it)
# Recomputes via the SAME evaluate_real_hardware.score_all() replay logic,
# pinned explicitly to gcn and m6_corrected -- not a second implementation.
# ---------------------------------------------------------------------------
def r13_hardware_score_distributions():
    import evaluate_real_hardware as E
    import relational_pin as rp

    rows = E.load_sessions("test")
    order = [p for p in ["at_rest", "gentle_tap", "tilt_rotate", "fault_weak",
                          "fault_strong", "sharp_impact", "moderate_shake"]]

    fig, axes = plt.subplots(1, 2, figsize=(12, 4.8), sharey=True)
    for ax, pin, title, color in [
        (axes[0], rp.GCN, "GCN", GREY),
        (axes[1], rp.M6_CORRECTED, "Corrected M6 (deployed)", CYAN),
    ]:
        scored = E.score_all(rows, pin)
        by = {}
        for r in scored:
            by.setdefault(r["phase"], []).append(r["fused"])
        present = [p for p in order if p in by]
        data = [by[p] for p in present]
        bp = ax.boxplot(data, vert=True, patch_artist=True, widths=0.6,
                         medianprops=dict(color="black", linewidth=1.4))
        for patch, p in zip(bp["boxes"], present):
            patch.set_facecolor(CYAN if p == "at_rest" else color)
            patch.set_alpha(0.65)
        ax.axhline(0.6, color=RED, ls="--", lw=1.1, label="threshold 0.6")
        ax.set_xticks(range(1, len(present) + 1))
        ax.set_xticklabels(present, rotation=35, ha="right", fontsize=8)
        ax.set_title(title, fontsize=9)
        ax.legend(fontsize=7)
        ax.grid(axis="y", alpha=0.25)
    axes[0].set_ylabel("Fused Process Trust score")
    fig.suptitle("R13: Real hardware fused-score distribution by phase — GCN vs. corrected M6\n"
                 "(held-out TEST session, same replay logic as evaluate_real_hardware.py)", y=1.04)
    savefig(fig, "r13_hardware_score_distributions.png")


# ---------------------------------------------------------------------------
# R15 -- Seed / statistical robustness (Optional)
# ---------------------------------------------------------------------------
def r15_seed_robustness():
    pe = rj("results/crossdevice_benchmark/seed_study.json")["paired_effects"]["degree"]
    models = list(pe.keys())
    means = [pe[m]["mean_delta"] for m in models]
    # M3/M6 have zero variance across seeds (sd=0.0, "note" field instead of a
    # t-interval) -- a genuinely zero-width interval, not missing data.
    ci95 = [pe[m].get("ci95", [pe[m]["mean_delta"], pe[m]["mean_delta"]]) for m in models]
    lo = [mean - c[0] for mean, c in zip(means, ci95)]
    hi = [c[1] - mean for mean, c in zip(means, ci95)]
    colors = [CYAN if "M6" in m else (RED if "M4" in m else VIOLET) for m in models]
    labels = [m.split("_", 1)[1].replace("_", " ") for m in models]

    fig, ax = plt.subplots(figsize=(7, 4.4))
    y = np.arange(len(models))
    ax.errorbar(means, y, xerr=[lo, hi], fmt="o", capsize=4, color="black", zorder=3)
    for yi, c in zip(y, colors):
        ax.scatter(means[yi], yi, color=c, s=60, zorder=4)
    ax.axvline(0, color="grey", ls="--", lw=1)
    ax.set_yticks(y)
    ax.set_yticklabels(labels, fontsize=8)
    ax.invert_yaxis()
    ax.set_xlabel("Mean recall delta, degree 1→9 (10 seeds, 95% t-interval)")
    ax.set_title("R15: Seed/statistical robustness — target-degree effect\n"
                  "(paired refits, df=9, doc 13 D/E)")
    ax.grid(axis="x", alpha=0.25)
    savefig(fig, "r15_seed_robustness.png")


# ---------------------------------------------------------------------------
# Paper-ready figure set (2026-09-07, refined priority pass). Supersedes
# R1/R3/R4/R5/R6/R14 above with more precisely specified panels -- those six
# were removed (not just left redundant) to avoid two figures answering the
# same question differently. R2/R7/R8/R9/R10/R11/R12/R13/R15 are unaffected
# and still generated.
# ---------------------------------------------------------------------------

def model_performance_comparison():
    """MUST HAVE -- the main model-performance figure. (a) standalone + fusion
    Macro-F1 across the three relational-model arms, (b) Task-2 5-method
    comparison. Combines what R1/R3/R8 showed separately into the one figure
    a reader needs for the headline GCN-vs-corrected-M6 result."""
    standalone = rj("results/gcn_m6_corrected_comparison/standalone_comparison.json")["results"]
    fusion = rj("results/gcn_m6_corrected_comparison/fusion_comparison.json")["results"]
    task2 = rj("results/gcn_m6_corrected_comparison/task2_comparison.json")["task2_network_coordination_pattern_4way_accuracy"]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4.8))

    # (a) standalone + fusion Macro-F1, grouped by arm
    arms = ["gcn", "m6_deployed", "m6_corrected"]
    x = np.arange(2)  # [Standalone, Fusion]
    width = 0.26
    for i, arm in enumerate(arms):
        vals = [standalone[arm]["macro_f1"], fusion[arm]["macro_f1"]]
        xi = x + (i - 1) * width
        ax1.bar(xi, vals, width, label=ARM_LABEL[arm], color=ARM_COLOR[arm])
        for xj, v in zip(xi, vals):
            ax1.text(xj, v + 0.015, f"{v:.4f}", ha="center", fontsize=7.5, rotation=90)
    ax1.set_xticks(x)
    ax1.set_xticklabels(["Standalone", "Fusion"])
    ax1.set_ylabel("Macro-F1")
    ax1.set_ylim(0, 1.0)
    ax1.set_title("(a) Standalone + fusion Macro-F1")
    ax1.legend(fontsize=8)
    ax1.grid(axis="y", alpha=0.25)

    # (b) Task-2 5-method comparison, TEST accuracy
    order = ["B0_anomalous_node_count", "B1_concat_logreg", "B2_concat_mlp",
             "GNN_node_embeddings", "M6_node_embeddings"]
    labels = ["B0", "B1", "B2", "GCN", "Corrected\nM6"]
    colors2 = [GREY, VIOLET, AMBER, RED, CYAN]
    vals2 = [task2[k]["test"] for k in order]
    bars = ax2.bar(labels, vals2, color=colors2)
    for b, v in zip(bars, vals2):
        ax2.text(b.get_x() + b.get_width() / 2, v + 0.01, f"{v:.4f}", ha="center", fontsize=8)
    ax2.set_ylabel("Task-2 4-way accuracy")
    ax2.set_ylim(0, 0.72)
    ax2.set_title("(b) Task-2 five-method comparison")
    ax2.grid(axis="y", alpha=0.25)

    fig.suptitle("Corrected GCN vs. M6 Set Transformer performance\n"
                 "(held-out replay, doc 13 O4/N — standalone 0.7926, fusion 0.5798 vs 0.5679, Task-2 0.5983 vs 0.5375)",
                 y=1.05)
    savefig(fig, "model_performance_gcn_vs_m6.png")


def policy_action_performance():
    """MUST HAVE. Grouped bar: ALLOW/ALERT/STEP_UP/BLOCK x Precision/Recall/F1,
    for the DEPLOYED corrected-M6 policy -- a single-arm diagnostic (not a
    GCN-vs-M6 comparison; that's R4's job... except R4 is retired, and this
    is deliberately the one that stays, since 'what does the deployed policy
    actually do' is the more paper-relevant question than the marginal
    GCN-baseline delta)."""
    d = rj("results/m6_corrected_policy/policy_action_metrics.json")["m6_corrected"]
    actions = ["ALLOW", "ALERT", "STEP_UP", "BLOCK"]
    metrics = ["precision", "recall", "f1"]
    colors = {"precision": VIOLET, "recall": CYAN, "f1": AMBER}

    fig, ax = plt.subplots(figsize=(8, 4.8))
    x = np.arange(len(actions))
    width = 0.26
    for i, m in enumerate(metrics):
        vals = [d[a][m] for a in actions]
        xi = x + (i - 1) * width
        ax.bar(xi, vals, width, label=m.capitalize(), color=colors[m])
        for xj, v in zip(xi, vals):
            ax.text(xj, v + 0.015, f"{v:.2f}", ha="center", fontsize=7.5)
    ax.set_xticks(x)
    ax.set_xticklabels(actions)
    ax.set_ylim(0, 1.1)
    ax.set_ylabel("Value")
    ax.set_title("Deployed (corrected-M6) policy — per-action precision/recall/F1\n"
                 "(test_session.json, deterministic clock, doc 13 O5)")
    ax.legend(fontsize=8)
    ax.grid(axis="y", alpha=0.25)
    ax.annotate("BLOCK is unreachable\n(architectural, see 18)", xy=(3, 0.03), xytext=(2.3, 0.35),
                fontsize=8, ha="center", arrowprops=dict(arrowstyle="->", color=RED), color=RED)
    savefig(fig, "policy_action_performance.png")


def hardware_validation():
    """HIGH PRIORITY. Compact rate/count plot for the deployed (corrected-M6)
    arm: both disturbance detection AND resting false positives shown
    together with sample sizes printed directly -- never just the flattering
    100% detection number alone."""
    d = rj("results/gcn_m6_corrected_comparison/hardware_comparison.json")["results"]["m6_corrected"]
    fp = d["resting_false_positive_rate"]
    det = d["disturbance_detection_rate"]

    fig, ax = plt.subplots(figsize=(5.5, 4.6))
    labels = ["Disturbance\ndetection", "Resting\nfalse positives"]
    vals = [det["rate"], fp["rate"]]
    lo = [det["rate"] - det["wilson_95ci"][0], fp["rate"] - fp["wilson_95ci"][0]]
    hi = [det["wilson_95ci"][1] - det["rate"], fp["wilson_95ci"][1] - fp["rate"]]
    counts = [f"{det['k']}/{det['n']}", f"{fp['k']}/{fp['n']}"]
    bars = ax.bar(labels, vals, yerr=[lo, hi], capsize=5, color=[CYAN, RED], width=0.55)
    for b, v, hv, c in zip(bars, vals, hi, counts):
        ax.text(b.get_x() + b.get_width() / 2, v + hv + 0.04, c,
                ha="center", fontsize=11, fontweight="bold")
    ax.set_ylim(0, 1.2)
    ax.set_ylabel("Rate (Wilson 95% CI)")
    ax.set_title("Physical hardware validation — deployed corrected-M6\n"
                 "(real MPU6050, held-out TEST session, 42 scored windows)")
    ax.grid(axis="y", alpha=0.25)
    savefig(fig, "hardware_validation.png")


def local_detector_attack_class_recall():
    """HIGH PRIORITY. Rule / Isolation Forest / LSTM-AE only (the three local,
    per-message detectors this system deliberately keeps rather than
    replacing with one model) across Shock/Coordinated/Stealthy -- shows
    why multiple local detectors are retained: no single one wins every
    class. [GCN-era preserved replay, doc 13 A -- see r6's retired docstring
    for the same honesty note; no post-M6 rerun of this exact per-signal
    breakdown exists]."""
    signals = ["rule_score", "isolation_forest_score", "lstm_ae_score"]
    signal_labels = ["Rule", "Isolation Forest", "LSTM-AE"]
    events = ["Shock", "Coordinated", "Stealthy"]
    # source: results/final_verification/local_fusion_evaluation.log,
    # "Per-event-type recall" table (anomalous_shock/coordinated/stealthy_forged_values).
    recall = {
        "rule_score":             [0.000, 0.000, 0.000],
        "isolation_forest_score": [1.000, 0.316, 0.212],
        "lstm_ae_score":          [1.000, 0.308, 0.606],
    }
    colors = [GREY, "#38bdf8", "#818cf8"]

    fig, ax = plt.subplots(figsize=(7, 4.6))
    x = np.arange(len(events))
    width = 0.24
    for i, s in enumerate(signals):
        xi = x + (i - 1) * width
        ax.bar(xi, recall[s], width, label=signal_labels[i], color=colors[i])
        for xj, v in zip(xi, recall[s]):
            ax.text(xj, v + 0.02, f"{v:.2f}", ha="center", fontsize=8)
    ax.set_xticks(x)
    ax.set_xticklabels(events)
    ax.set_ylim(0, 1.15)
    ax.set_ylabel("Recall (event correctly flagged suspicious)")
    ax.set_title("Local-detector attack-class recall — why three detectors are kept\n"
                 "[GCN-era preserved replay, doc 13 A]")
    ax.legend(fontsize=8)
    ax.grid(axis="y", alpha=0.25)
    savefig(fig, "local_detector_attack_class_recall.png")


def m6_training_correction():
    """OPTIONAL / discussion-ablation figure. Flawed vs corrected M6
    checkpoint standalone Macro-F1, plus the class-weight numbers that
    caused it (45.18 buggy vs 6.27 correct suspicious-class weight)."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(9.5, 4.4))

    ax1.bar(["Flawed\ncheckpoint", "Corrected\ncheckpoint"], [0.0735944, 0.7925591],
            color=[RED, CYAN])
    for i, v in enumerate([0.0735944, 0.7925591]):
        ax1.text(i, v + 0.02, f"{v:.4f}", ha="center", fontsize=9)
    ax1.set_ylim(0, 1.0)
    ax1.set_ylabel("Standalone Macro-F1")
    ax1.set_title("(a) Standalone Macro-F1")
    ax1.grid(axis="y", alpha=0.25)

    ax2.bar(["Buggy weight\n(unmasked count)", "Correct weight\n(valid-only count)"],
            [45.18, 6.27], color=[RED, CYAN])
    for i, v in enumerate([45.18, 6.27]):
        ax2.text(i, v + 0.8, f"{v:.2f}", ha="center", fontsize=9)
    ax2.set_ylabel("Suspicious-class weight (neg_weight)")
    ax2.set_title("(b) Class-weight magnitude (7.2x overweight)")
    ax2.grid(axis="y", alpha=0.25)

    fig.suptitle("M6 training correction — class-weight bug fix\n"
                 "(scripts/train_set_transformer.py, doc 13 O4)", y=1.03)
    savefig(fig, "m6_training_correction.png")


def pending_node_masking_correction():
    """OPTIONAL. Two panels: Task-1 F1 before/after the pending-node masking
    fix (a real DEGRADATION, reported honestly), and the false-positive count
    that moved with it, so the tradeoff is visible, not just the F1 number."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(9, 4.4))

    ax1.bar(["Before\n(pre-audit)", "After\n(corrected masking)"], [0.9662, 0.9174],
            color=[AMBER, VIOLET])
    for i, v in enumerate([0.9662, 0.9174]):
        ax1.text(i, v + 0.01, f"{v:.4f}", ha="center", fontsize=9)
    ax1.set_ylim(0, 1.05)
    ax1.set_ylabel("Task-1 anomaly F1 (B2 concat MLP)")
    ax1.set_title("(a) Task-1 F1")
    ax1.grid(axis="y", alpha=0.25)

    ax2.bar(["Before\n(pre-audit)", "After\n(corrected masking)"], [28, 270],
            color=[AMBER, VIOLET])
    for i, v in enumerate([28, 270]):
        ax2.text(i, v + 5, str(v), ha="center", fontsize=9)
    ax2.set_ylabel("False positives (of 22,800 test rows)")
    ax2.set_title("(b) False positives (FN moved 72→0 the other way)")
    ax2.grid(axis="y", alpha=0.25)

    fig.suptitle("Pending-node / B2 masking correction — a real tradeoff, not a pure win\n"
                 "(doc 13 N, Task-1 B2 degradation status table)", y=1.03)
    savefig(fig, "pending_node_masking_correction.png")


PAPER_FIGURES = [
    model_performance_comparison, policy_action_performance, hardware_validation,
    local_detector_attack_class_recall, m6_training_correction,
    pending_node_masking_correction,
]

ALL_FIGURES = [
    r2_m1_m9_benchmark, r7_latency, r8_fusion_comparison, r9_topology_sensitivity,
    r10_generator_validity, r11_explainability_contributions,
    r12_policy_confusion_matrix, r13_hardware_score_distributions,
    r15_seed_robustness,
] + PAPER_FIGURES


def main():
    for fn in ALL_FIGURES:
        fn()
    print(f"\n{len(ALL_FIGURES)} figures written to {FIGURES_DIR}")


if __name__ == "__main__":
    main()
